UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 1;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 2;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 3;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 4;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 5;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 6;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 7;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 8;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 9;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 10;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 11;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 12;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 13;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 14;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 15;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 16;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 17;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 18;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 19;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 20;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 21;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 22;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 23;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 24;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 25;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 26;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 27;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 28;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 29;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 30;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 31;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 32;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 33;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 34;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 35;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 36;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 37;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 38;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 39;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 40;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 41;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 42;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 43;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 44;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 45;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 46;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 47;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 48;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 49;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 50;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 51;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 52;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 53;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 54;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 55;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 56;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 57;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 58;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 59;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 60;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 61;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 62;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 63;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 64;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 65;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 66;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 67;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 68;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 69;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 70;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 71;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 72;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 73;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 74;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 75;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 76;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 77;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 78;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 79;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 80;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 81;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 82;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 83;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 84;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 85;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 86;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 87;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 88;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 89;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 90;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 91;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 92;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 93;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 94;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 95;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 96;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 97;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 98;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 99;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 100;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 101;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 102;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 103;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 104;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 105;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 106;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 107;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 108;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 109;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 110;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 111;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 112;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 113;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 114;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 115;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 116;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 117;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 118;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 119;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 120;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 121;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 122;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 123;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 124;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 125;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 126;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 127;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 128;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 129;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 130;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 131;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 132;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 133;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 134;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 135;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 136;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 137;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 138;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 139;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 140;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 141;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 142;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 143;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 144;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 145;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 146;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 147;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 148;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 149;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 150;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 151;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 152;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 153;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 154;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 155;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 156;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 157;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 158;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 159;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 160;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 161;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 162;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 163;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 164;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 165;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 166;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 167;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 168;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 169;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 170;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 171;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 172;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 173;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 174;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 175;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 176;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 177;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 178;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 179;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 180;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 181;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 182;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 183;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 184;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 185;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 186;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 187;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 188;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 189;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 190;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 191;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 192;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 193;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 194;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 195;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 196;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 197;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 198;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 199;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 200;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 201;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 202;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 203;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 204;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 205;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 206;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 207;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 208;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 209;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 210;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 211;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 212;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 213;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 214;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 215;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 216;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 217;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 218;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 219;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 220;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 221;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 222;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 223;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 224;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 225;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 226;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 227;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 228;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 229;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 230;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 231;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 232;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 233;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 234;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 235;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 236;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 237;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 238;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 239;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 240;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 241;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 242;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 243;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 244;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 245;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 246;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 247;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 248;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 249;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 250;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 251;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 252;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 253;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 254;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 255;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 256;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 257;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 258;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 259;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 260;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 261;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 262;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 263;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 264;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 265;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 266;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 267;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 268;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 269;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 270;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 271;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 272;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 273;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 274;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 275;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 276;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 277;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 278;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 279;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 280;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 281;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 282;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 283;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 284;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 285;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 286;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 287;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 288;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 289;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 290;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 291;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 292;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 293;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 294;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 295;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 296;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 297;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 298;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 299;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 300;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 301;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 302;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 303;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 304;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 305;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 306;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 307;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 308;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 309;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 310;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 311;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 312;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 313;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 314;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 315;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 316;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 317;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 318;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 319;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 320;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 321;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 322;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 323;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 324;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 325;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 326;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 327;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 328;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 329;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 330;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 331;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 332;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 333;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 334;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 335;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 336;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 337;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 338;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 339;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 340;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 341;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 342;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 343;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 344;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 345;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 346;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 347;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 348;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 349;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 350;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 351;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 352;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 353;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 354;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 355;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 356;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 357;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 358;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 359;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 360;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 361;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 362;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 363;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 364;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 365;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 366;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 367;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 368;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 369;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 370;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 371;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 372;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 373;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 374;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 375;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 376;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 377;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 378;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 379;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 380;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 381;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 382;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 383;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 384;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 385;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 386;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 387;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 388;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 389;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 390;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 391;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 392;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 393;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 394;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 395;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 396;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 397;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 398;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 399;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 400;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 401;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 402;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 403;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 404;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 405;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 406;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 407;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 408;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 409;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 410;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 411;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 412;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 413;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 414;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 415;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 416;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 417;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 418;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 419;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 420;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 421;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 422;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 423;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 424;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 425;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 426;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 427;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 428;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 429;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 430;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 431;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 432;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 433;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 434;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 435;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 436;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 437;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 438;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 439;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 440;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 441;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 442;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 443;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 444;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 445;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 446;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 447;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 448;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 449;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 450;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 451;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 452;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 453;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 454;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 455;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 456;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 457;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 458;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 459;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 460;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 461;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 462;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 463;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 464;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 465;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 466;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 467;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 468;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 469;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 470;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 471;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 472;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 473;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 474;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 475;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 476;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 477;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 478;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 479;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 480;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 481;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 482;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 483;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 484;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 485;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 486;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 487;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 488;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 489;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 490;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 491;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 492;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 493;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 494;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Dolares' WHERE `customer_id` = 495;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 496;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 497;
UPDATE `cuenta` SET `tipoCuenta` = 'Caja de Ahorro en Pesos' WHERE `customer_id` = 498;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 499;
UPDATE `cuenta` SET `tipoCuenta` = 'Cuenta Corriente' WHERE `customer_id` = 500;
