# Generated by Django 4.0.6 on 2022-08-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_delete_prestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
    ]
