# Generated by Django 4.0.6 on 2022-08-13 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='iddirecciones',
            field=models.ForeignKey(blank=True, db_column='idDirecciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.sujetodireccion'),
        ),
    ]
