# Generated by Django 4.0.6 on 2022-08-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_cliente_tipocliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
    ]
