# Generated by Django 4.0.6 on 2022-08-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
