# Generated by Django 4.0.6 on 2022-08-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_cliente_usuario'),
        ('Prestamos', '0004_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
